### ISSUE TITLE
Fixing Map Delay and Refining Search

### ISSUE THREAD

**Issue by JJBai2003** [cornellh4i/EDGI_Website#13]
## Section 1. Map delay fix
Overview:
As you may have noticed, the map does have a delay. This is because each time the user is interacting with the map, the map tries to load all the data again. One way to fix this issue is by using caching, where we store the data locally so that the map doesn’t have to load it all again, and then reload/update the data only when we absolutely need to do so. 
Here is an example of how we might approach structuring a Streamlit website in order to minimize the data reload/refresh problem. This is a problem inherent to the Streamlit framework, as it is meant to re-execute the script when a user interacts with the page (just as the "page" on a Colab Jupyter Notebook would update when you click play on a cell of code). That's a good thing! We want the script to re-execute when a user selects a new county, for instance. It's a bad thing when we end up re-running everything even when we don't need to.
### Tasks:
Pre-Part 1: 

- [x] Create a new branch appropriately named.

Part 1:

- [x]  We will be trying to optimize data retrieval in searchbox.py (the file where you have your searchbox/map searching) 
- Reference https://github.com/ericnost/ECHO_Facilities (pay attention to the dependencies in the pipfile) and try to modify the data retrieval. This is the resulting website https://echofacilities.streamlit.app/

- [x] Keep in mind that each change of state/county is making several hits against a database, asking for somewhat significant chunks of data (facilities, EJScreen data, county boundaries) so it won't be super quick. But with some control logic, it will not be re-loading everything.

Part 2: Color Change for Searched State/County 
We want to implement the following flow that the designers have on Figma: Search state/county → hover over → changes color

- [x] This should be a similar idea to the region outlining that you guys worked on last sprint. We’re also just highlighting it too. You may want to reference the https://github.com/edgi-govdata-archiving/ECHO_modules/blob/main/ECHO_modules/utilities.py ‘s bivariate_map method which you guys are familiar with). 

- Here is another component that allow us to do so: https://python-visualization.github.io/folium/latest/user_guide/geojson/geojson.html
