### ISSUE TITLE
Data Extraction from Region.db into Streamlit Part 2

### ISSUE THREAD

**Issue by jessicajcho** [cornellh4i/EDGI_Website#2]
This week’s sprint is going to be a continuation of the work you guys have done for the last sprint. After successfully importing the necessary files and repositories, we will start preparing for more complicated features that will be useful when migrating data to Streamlit. 

**Part I:**
- Finish up the last sprint. 
- Please let both of us know if you guys are having any trouble so we can set up a time to help :^)

**Part II:** 

- Run the rest of the sections( section 5 - 7), and pay attention to the code used to create widgets. 
- [ ] Within region_data.py, the file that you guys created for part I of the sprint, populate the code in section 5 - 7 in Streamlit. (Note: Some cells depend on the previous selections so make sure you choose something for each selector to avoid error)

- For creating selectors in Streamlit, reference: https://docs.streamlit.io/library/api-reference/widgets/st.selectbox 
- After creating all the selectors, take a look at section 3. Notice how the State and County are hard coded(i.e this_state = ‘NY’).  We do not want to do that for every single county. Therefore, we want you guys to make the code more accessible by incorporating the selectors that you guys have created above. 
- Namely, we want to display the same statistics but for user-chosen states and counties.

**Publishing:**

- [ ] Make sure that all the code works by playing around with the selector and cross-validating with the google colab

- [ ] Commit and push your branch

- [ ] Create a Pull Request and DOUBLE CHECK the base repository is set to cornellh4i/EDGI_Website

DONE! Good job!!
