### ISSUE TITLE
Code Review and Streamlit Search Bar implementation

### ISSUE THREAD

**Issue by jessicajcho** [cornellh4i/EDGI_Website#5]
For this week, we want to try something a bit different. Before we release the new tasks for this week, we would like to merge the branches with the best version of the tickets. Therefore, the sprint will be separated into two portions: Code Review & New Tasks. Once the first portion is done, we will merge and release the second portion.

### Part I. Review, Understand and Improve
We will incorporate the code review portion into our tickets. We want to emphasize the importance of the readability of our code base since EDGI is a continuing project, and we would like our “successors” to intuitively understand what has been done. This leads us to the Part I of our sprint.

Review + Understand:
- You guys are going to review Hubert and Brianna's ticket from last week. The PR can be found here: 
https://github.com/cornellh4i/H4I_EEW_Industry_Reports/pull/13
- Navigate to the corresponding repo and find the ticket
- If you are at the correct PR page, you should be able to see a green button at the top right that says “Add Your Review”
- Clicking the button will bring you to a review page, which probably consists of a bunch of random json blocks if you are reviewing a jupyter notebook file. In that case, click the three dots at the right corner and open in a new tab “View File”. Now you should be able to see the actual jupyter notebook file.
- Note: Unfortunately github’s code review doesn’t do a great job supporting inline comments like other files. If you see anything that you would like to comment on, just put the line number before your comments to make it more clear.

- Add comments by clicking on the “Review change” button, keeping in mind the following guidelines:
- Before you write any comments, make sure you understand what the other group’s work is about. It might be helpful to refer to the ticket instructions and the resources listed. 
> Try to minimize the use of “good job” or “nice work” - it’s nice to put at the beginning of your review, but to ensure that each comment is constructive
> Identify any issues with code
> - Formatting
> -  Logical
> - Bug
> - Compilation
> Describe in detail what the issue is - how did you come across it? Through looking at their code or manually testing a feature?
> What can they do to resolve the issue? Is it a simple fix? Do you have a recommendation?

Improve:
- Now you should have received your code review from your reviewer.
- Go through the reviews carefully and make changes to your code if applicable. (All the changes should be done in the same branch as the one you made your PR from)
- When you are done, commit and push your code (The PR should automatically be updated with the latest version of the code after you push to the same branch, so no need to make a new one)

Please have this done ASAP so we can merge :) Good luck and have fun! Hopefully you will have a good understanding of how the project as a whole is going after this portion. If you have any questions about the code review logistics, or the sprints that you are reviewing, don’t hesitate to slack us! 

### Part 2: Implement Streamlit Search

The goal of this sprint is to get the search box / fuzzy search to work– so that the user can search up either the county or the state. 

- [x] Create a new branch that is appropriately named in local terminal or VSCode terminal. EDIT: since you can potentially work off of your current branch from last sprint, you can just use that existing branch instead. 
- [x] Refer to this link https://github.com/m-wrzr/streamlit-searchbox/tree/main for implementing the search bar itself. You will need to connect the search bar to the database that contains information about the state and county, so that when the user types in some input, the search bar will have some sort of dropdown with suggestions based on the user’s text. 
- This is the same idea as what you did last sprint with creating the state/county widgets. 
- Reference the Figma page→ go to Figma (mobile or app is fine) and log in w/ your Cornell email. Navigate to the Cornell Hack Figma organization → click on EDGI Figma file. (this should be accessible to you, let us know if that is not the case). For now, don't worry too much about making it look exactly like the search bar in the Figma. 
- [] Now, we’re going to try to get the information from the SBU database relating to the specific state or county on the Streamlit website. Make sure that the information is displayed / updated when the user types in a diff. input in the search bar. 

After finishing the code:
- [x] Commit and push your branch
- [x] Create a Pull Request to this EDGI_Website Repo (**not the Cornell EEW_ReportCards repo**)
- DONE! Good job! 🍾
