### ISSUE TITLE
Map Expansion & Side Bar Implementation

### ISSUE THREAD

**Issue by jessicajcho** [cornellh4i/EDGI_Website#9]
For this sprint, we would like to refine our components to be more aligned with the design, and connect the search bar to the map. 

### Part I. Review, Understand and Improve
Review + Understand:
- Each pair will be assigned to review one other pairs’ ticket from last week(refer to the list below) 
- You will be looking at Anya/Owen's PR from last week. 
- Navigate to the corresponding repo and find the ticket
- If you are at the correct PR page, you should be able to see a green button at the top right that says “Add Your Review”
- Add comments by clicking on the “Review change” button, keeping in mind the following guidelines:
- Before you write any comments, make sure you understand what the other group’s work is about. It might be helpful to refer to the ticket instructions and the resources listed. 
- Try to minimize the use of “good job” or “nice work” - it’s nice to put at the beginning of your review, but to ensure that each comment is constructive
- Identify any issues with code
  - Formatting 
  - Logical
  - Bug
  - Compilation
- Describe in detail what the issue is - how did you come across it? Through looking at their code or manually testing a feature?
What can they do to resolve the issue? Is it a simple fix? Do you have a recommendation?

Improve:
Now you should have received your code review from your reviewer.
Go through the reviews carefully and make changes to your code if applicable. (All the changes should be done in the same branch as the one you made your PR from)
When you are done, commit and push your code (The PR should automatically be updated with the latest version of the code after you push to the same branch, so no need to make a new one)

### Part 2. Side Bar

- [x] Create the “guide” side bar: 
- Refer to the Figma for the specific details. Essentially, there should be a button near the bottom left of the page, which when pressed, opens a sidebar that reveals the “user guide” for the website. 

- [x] Create the data visualization side bar: 
- Here, we want to implement the feature where if a user clicks on a specific county search result underneath the search box, we want to display the corresponding information in the sidebar. 
- Refer to the Figma page for the necessary components → including the different tabs. 
- Use the Streamlit sidebar & tab components to implement the sidebar. 
- For now, since the state/county selection is not finalized (being worked on in a different sprint, we cannot necessarily use the search bar result). However, when creating the styling, make sure that it is generalizable to any arbitrary state/county or facility that is being passed in.
- For now, you can use a temporary widget/selectbox (see Owen/Anya’s sprint https://github.com/cornellh4i/EDGI_Website/pull/7) and toggle the user input in that way.

- [x] Display the SBU data (specifically the environmental justice data) in the appropriate place on the sidebar.
- Don’t worry about the data (from the Region.db) database for now. This can be filled in later. 
- [x] Expand the map. 
- Per the design, the map on the Streamlit website fills up the entire space of the website. 
- Create a Streamlit-Folium map (you can reference the notebook for creating the map specific to our website https://colab.research.google.com/drive/1-94zaUeDB-qPd4QJ2PNF7x1yz_rdVUuL?usp=sharing#scrollTo=SJBe9ujdrZyU or it is also fine to use a dummy map). Now, the goal is to have this map fill up the entire screen. Make sure that the sidebar / other website components are still visible. Note: It might be helpful to look into CSS functions.

### Part 3: 
- Remove unneeded code / Add documentation as needed 
- Commit all changes
- Create a pull request to the correct repo. GOOD JOB 🥂
